spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.gate.syldavia.eu:8080/realms/eFTI_SY

server:
  port: 8071

gate:
  minSleep: 1000
  maxSleep: 2000
  owner: massivedynamic
  cda_path: .cda/
  gate: syldavia
  ap:
    url: http://efti.platform.massivedynamic.com:81/domibus/services/wsplugin
    username: massivedynamic_service_account
    password: Azerty59*1234567

mock:
  badRequestPercentage: 0.0f
  gaussWaitingTime:
    average: 10
    standardDeviation: 5
    isActiveForIdentifierRequestTimer: false
    isTimerActiveForIdentifierResponse: false
  identifierReponseGoodResponse:
    description: description
    status: 200
  identifierReponseBadResponse:
    description: bad gateway
    status: 404

feign-gate:
  name: call-gate-identifiers
  url: http://host.docker.internal:8882
  keycloak: http://auth.gate.syldavia.eu:8080/realms/eFTI_SY/protocol/openid-connect/token
  clientid: platform-sy
  clientsecret: 58mMDEIs9OAcwqrn3gMrwAIU7tPc0msC
