spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.gate.listenbourg.eu:8080/realms/eFTI_LI

server:
  port: 8072

gate:
  minSleep: 1000
  maxSleep: 2000
  owner: umbrellainc
  cda_path: cda/
  gate: listenbourg
  ap:
    url: http://efti.platform.umbrellainc.com:81/domibus/services/wsplugin
    username: umbrellacorporation_service_account
    password: Azerty59*1234567

mock:
  badRequestPercentage: 0.0f
  gaussWaitingTime:
    average: 10
    standardDeviation: 5
    isActiveForIdentifierRequestTimer: false
    isTimerActiveForIdentifierResponse: false
  identifierReponseGoodResponse:
    description: description
    status: 200
  identifierReponseBadResponse:
    description: bad gateway
    status: 404
