spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.gate.listenbourg.eu:8080/realms/eFTI_FR

server:
  port: 8072

gate:
  minSleep: 1000
  maxSleep: 2000
  owner: ttf
  cda_path: classpath:cda/
  gate: france
  ap:
    url: http://efti.platform.ttf.com:81/domibus/services/wsplugin
    username: ttf_service_account
    password: Azerty59*1234567

