spring:
  rabbitmq:
    password: syldavia
    username: syldavia
    virtual_host: syldavia
    host: svc-efti-rabbitmq.app-int-efti
  application:
    name: efti-gate-sy
  datasource:
    url: jdbc:postgresql://ileftidbpg01in.service.groupein.local:5432/efti
    username: efti
    password: j6h6BEjpHIwYly7HA0z
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer_uri: https://keycloak.efti.int.k8s.groupein.local/realms/eFTI_SY
  jpa:
    properties:
      hibernate:
        control_schema: "eftisy"
        identifiers_schema: "metadatasy"

gate:
  owner: syldavia
  country: SY
  ap:
    url: http://ileftimicr03in.service.groupein.local:8080/domibus/services/wsplugin
    username: syldavia_service_account
    password: Azerty59*1234567
  xsd:
    path: /opt/javapp/schema/xsd/edelivery/gate.xsd

batch:
  retry:
    cron: "*/20 * * * * *"
    time: 20, 120, 300
    size: 10

springdoc:
  swagger_ui:
    enabled: true
  api_docs:
    enabled: true
