spring:
  rabbitmq:
    password: bo
    username: bo
    virtual-host: bo
  datasource:
    control:
      liquibase:
        default-schema: eftibo
        change-log: classpath:db.changelog/db.gate.changelog-master.xml
    identifiers:
      liquibase:
        default-schema: eftibo
        change-log: classpath:db.changelog/db.identifiers.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.gate.borduria.eu:8080/realms/eFTI_BO
  jpa:
    properties:
      hibernate:
        control_schema: "eftibo"
        identifiers_schema: "eftibo"

gate:
  owner: http://efti.gate.borduria.eu
  country: BO
  ap:
    url: http://efti.gate.borduria.eu:81/domibus/services/wsplugin
    username: borduria_service_account
    password: Azerty59*1234567
