spring:
  rabbitmq:
    password: li
    username: li
    virtual-host: li
  datasource:
    control:
      liquibase:
        default-schema: eftili
        change-log: classpath:db.changelog/db.gate.changelog-master.xml
    identifiers:
      liquibase:
        default-schema: eftili
        change-log: classpath:db.changelog/db.identifiers.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.gate.listenbourg.eu:8080/realms/eFTI_LI
  jpa:
    properties:
      hibernate:
        control_schema: "eftili"
        identifiers_schema: "eftili"

gate:
  owner: http://efti.gate.listenbourg.eu
  country: LI
  ap:
    url: http://efti.gate.listenbourg.eu:81/domibus/services/wsplugin
    username: listenbourg_service_account
    password: Azerty59*1234567

server:
  port: 8881