spring:
  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        javax:
          cache:
            provider: com.hazelcast.cache.impl.HazelcastServerCachingProvider
            uri: hazelcast.xml
            missing_cache_strategy: create
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  rabbitmq:
    host: localhost
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 6
          max-interval: 10s
          multiplier: 2
        concurrency: 10
    port: 5672
    queues:
      eftiKeySendMessage: EFTI
      eftiSendMessageExchange: efti.send-message.exchange
      eftiReceiveMessageExchange: efti.receive-message.exchange
      eftiSendMessageQueue: efti.send-messages.q
      eftiReceiveMessageQueue: efti.receive-messages.q
      messageSendDeadLetterQueue: message-send-dead-letter-queue
      messageReceiveDeadLetterQueue: message-receive-dead-letter-queue
  application:
    name: efti-gate
  datasource:
    control:
      jdbc-url: jdbc:postgresql://localhost:9000/efti
      url: jdbc:postgresql://localhost:9000/efti
      username: ingroup
      password: root
      driverClassName: org.postgresql.Driver
      liquibase:
        change-log: classpath:db.changelog/db.gate.changelog-master.xml
    identifiers:
      jdbc-url: jdbc:postgresql://localhost:2345/efti
      url: jdbc:postgresql://localhost:2345/efti
      username: root
      password: root
      driverClassName: org.postgresql.Driver
      liquibase:
        change-log: classpath:db.changelog/db.identifiers.changelog-master.xml
  jackson:
    default-property-inclusion: NON_NULL

server:
  port: 8880

batch:
  update:
    cron: "0 */1 * ? * *"
  identifier:
    cron: "0 0 1 ? * *"
    activated: true
    deactivation-delay:
      three: 12
      other: 0
      null-delivery-date: 90

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

efti:
  control:
    pending:
      timeout: 60
logging:
  level:
    com:
      hazelcast:
        internal:
          diagnostics:
            HealthMonitor: OFF