name: Validate xml examples

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up
      run: sudo apt-get install -y xmlstarlet

    - name: Validate
      run: utils/validate-examples.sh
